### ISSUE TITLE
QMK firmware

### ISSUE THREAD

**Issue by geoah** [kata0510/MiniSplit#6]
Hey there @kata0510, thank you for open sourcing this.

I'm trying to get QMK to work on the minisplit and I'm having some issues getting the two parts to talk to each other.

Is there a QMK firmware for the minisplit available that you could link me to?

Thank you very much in advance.

**Comment by geoah** [comment]
Issue with this was that some traces seemed to be missing from my pcb print.

**Comment by sendz** [comment]
sorry for reopening the issue, I have similar issue with this

@geoah what is missing other than VCC from TRRS not connected? which pin do you use for `SOFT_SERIAL_PIN`?

SOLVED: My  promicro at right hand can't work as slave, switching the master to right hand and it works
